name: Methinks
favicon: null
layout_spectrum: 0.1546115055680275
typography_spectrum: 0.07452929229475558
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8188070757314563
  lightness: 0.9875290296040475
  saturation: 0.15038036974146962
  rhythmicContrast: 0.08442614693194628
purpose: []
