name: Methinks
favicon: null
layout_spectrum: 0.49823
typography_spectrum: 0
title: The Year of Stopping Dangerously
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75049530-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bed7f5'
    - '#030303'
    - '#232f00'
    - '#597175'
    - '#7c8eaf'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
